### ISSUE TITLE
YAML codeList format

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdCodes#1]
After considering whether to use YAML or JSON for the codeList file I went with YAML because it has less syntax and most importantly the syntax of YAML is mostly local to the line.  If we screw up a line of YAML it will likely only effect that line.  While a missed comma or bracket in JSON could cripple the whole file (which actually could make it easier to catch errors to un-support my decision to go with YAML). 

Below are two YAML format possibilities.  The second one carries a definition for the codeList as well as the items, the first only supports the list items.  Any preference? 

``` yaml
# adiwgJson codelists
# compiled from ISO 19115-2, 19115-2, NGDC, and ADIwg

---
associationType:
  - {id: "001", codeName: crossReference, codeDesc: reference from one resource (dataset or project) to another}
  - {id: "002", codeName: largerWorkCitation, codeDesc: reference to a master resource (dataset or project) of which this one is a part}

characterSet:
  - {id: "001", codeName: ucs2, codeDesc: "16-bit fixed size Universal Character Set, based on ISO/IEC 10646"}
  - {id: "002", codeName: ucs4, codeDesc: "32-bit fixed size Universal Character Set, based on ISO/IEC 10646"}

classification:
  classDesc: name of the handling restrictions on the dataset
  items:
    - {id: "001", codeName: unclassified, codeDesc: available for general disclosure}
    - {id: "002", codeName: restricted, codeDesc: not for general disclosure}
```
