### ISSUE TITLE
Add applicationProfile

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdCodes#29]
Based on list in https://www.geoplatform.gov/wp-content/uploads/2018/05/NGDA_Metadata_Guidelines_v3.pdf
 
```yaml
---
-
    code: 001
    codeName: http://opengis.net/spec/wms
    Description: OGC Web Map Service (WMS)
-
    code: 002
    codeName: http://opengis.net/spec/wfs
    Description:  OGC Web Feature Service (WFS)
-
    code: 003
    codeName: http://opengis.net/spec/wcs
    Description:  OGC Web Coverage Service (WCS)
-
    code: 004
    codeName: http://opengis.net/spec/wmts
    Description:  OGC Web Map Tile Service (WMTS)
-
    code: 005
    codeName: http://opengis.net/spec/csw
    Description:  OGC Catalog Service (CSW)
-
    code: 006
    codeName: http://opengis.net/spec/kml
    Description:  OGC Keyhole Markup Language (KML)
-
    code: 007
    codeName: http://www.geoplatform.gov/spec/esri-map-rest
    Description:  Esri REST Map Service
-
    code: 008
    codeName: http://www.geoplatform.gov/spec/esri-image-rest
    Description:  Esri REST Image Service
-
    code: 009
    codeName: http://www.geoplatform.gov/spec/esri-feature-rest
    Description:  Esri REST Feature Service
```
